#!/usr/bin/env python

#meld "$@" &> /dev/null &

import sys
import os
import subprocess

if len(sys.argv) > 1:
  left = os.path.abspath(sys.argv[1]);
else:
  left = ""

if len(sys.argv) > 2:
  right = os.path.abspath(sys.argv[2]);
else:
  right = ""

MELDPATH = "/Applications/Meld.app"
arguments = " -n " + MELDPATH + " --args " + left + " " + right

p = subprocess.call(['open', '-W', '-a',  MELDPATH, '--args', left, right])
