#!/usr/bin/env node

var stdout = '';
process.stdin.on('readable', function() {
  var chunk = process.stdin.read();
  if (chunk != null) {
    stdout += chunk;
  }
});

process.stdout.on('error', function( err ) {
  if (err.code == "EPIPE") {
    process.exit(0);
  }
});

process.stdin.on('end', function() {
  console.log(JSON.stringify(JSON.parse(stdout),null,4));
});
