#!/usr/bin/env node

var stdout = '';
process.stdin.on('readable', function() {
  var chunk = process.stdin.read();
  if (chunk != null) {
    stdout += chunk;
  }
});

process.stdin.on('end', function() {
  console.log(JSON.stringify(JSON.parse(stdout),null,4));
});
