#!/usr/bin/env bash

set +eox

rm -rf ~/.git
mv ~/bootstrap/.git ~/
cd ~/
echo "Resetting from $(pwd).."
git reset --hard HEAD
rm -rf bootstrap

# brew things
#brew install pcre
#brew reinstall --build-from-source git
