#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <in.mp3> [out.mp3]" 1>&2
  exit 1
fi

echo $#
for arg in "$@"; do

  in="$arg"
  shift
  echo "*** $in"

  time="$(stat -c '%z' "$in" | first)"

  out="$imu/$time-$(basename "$in" | pe 's/ /-/g' | tr '[A-Z]' '[a-z]' | pe 's/[^A-Za-z0-9\-.]//g')"
  echo "*** $out"
  echo ''

  ffmpeg -i "$in" -filter:a "atempo=1.5" -vn "$out"
done


# bitrate: -ab
