#!/usr/bin/env bash

if [ -z "$hhs" ]; then
  . refresh-hadoop-hosts
fi

if [[ $# -gt 0 ]]; then
  if [[ "$1" =~ ^[0-9]+$ ]]; then
    first=":$1"
  else
    first="$1"
  fi
  shift
else
  first=":"
fi
echo "$hhs" | splt ' ' | slice-lines "$first" "$@"
