#!/usr/bin/env bash

set -e

infile="$1"
shift
if [ $# -gt 0 ]; then
  outdir="$1"
  mkdir -p "$outdir"
else
  outdir=.
fi

td="$(mktemp -d)"

finish() {
  rm -rf "$td"
}
trap finish EXIT

split-into-files-by-regex '^>' "$td/fa" "$infile"
toggle-ifs
for f in "$td"/*; do
  chr="$(head -n 1 "$f" | perl -pe 's/^>([^\s]+).*/\1/')"
  outfile="$outdir/$chr.fasta"
  echo "$outfile"
  mv "$f" "$outfile"
done
toggle-ifs
