#!/usr/bin/env bash

if [ $# -gt 0 ]; then
  arg="$1"
  shift
  if [ "$arg" == "mgmt" -o "$arg" == "mgmt1" ]; then
    arg="mgmt1"
  elif [[ "$arg" =~ ^[0-9\-]*$ ]]; then
    arg=u"$arg"
  fi

  if [[ "$arg" =~ ^[uz][0-9\-]*$ ]]; then
    arg="csma$arg"
  fi

  ssh demeter-"$arg" "$@"
else
  ssh demeter
fi
