#!/bin/sh

set -xe

if [ $# -eq 1 ]; then
    if [ "$1" == "1" || "$1" == "2" ]; then
        fsq_web=$1
        host=
    else
        fsq_web=
        host=$1
    fi
elif [ $# -eq 0 ]; then
    host=
    fsq_web=
else
    fsq_web=$1
    host=$2
fi

if [ "$host" == "dc" ]; then
    host="fsad14:"
elif [ "$host" == "dev" ]; then
    host="build-5:"
fi

fsq_web="/Users/ryan/foursquare.web$fsq_web"
local_pex_path="/Users/ryan/pants.pex"
remote_pex_path="/home/ryan/pants.pex"

echo "Copying from $fsq_web$local_pex_path to $host$remote_pex_path"
exit 0
echo $fsq_web

if [ "$ONLYLINK" ]; then
    if [ ! -e $local_pex_path ]; then
        echo "No file at $local_pex_path"
        exit 1
    fi
else
    cd /Users/ryan/c/benjy-commons
    PANTS_DEV=1 ./pants src/python/twitter/pants/
    #mkdir -p $fsq_web/dist
    #cp dist/pants.pex $fsq_web/dist/
    cp dist/pants.pex $local_pex_path
fi

ln -sf $local_pex_path $fsq_web/build/pants.pex
ln -sf $local_pex_path $fsq_web/build/pants-current.pex
