#!/usr/bin/env bash

set -xe
#set -e

if [ $# -eq 1 ]; then
    if [ "$1" == "1" -o "$1" == "2" ]; then
        fsq_web=$1
        host=
    else
        fsq_web=
        host=$1
    fi
elif [ $# -eq 0 ]; then
    host=
    fsq_web=
else
    fsq_web=$1
    host=$2
fi

if [ "$host" == "dc" ]; then
    host="fsad14"
elif [ "$host" == "dev" ]; then
    host="build-5"
fi

fsq_web="/Users/ryan/c/foursquare.web$fsq_web"
local_pex_path="/Users/ryan/pants.pex"
remote_pex_path="/home/ryan/pants.pex"
pants_dir="/Users/ryan/c/commons"

echo "Building in $fsq_web\c"
if [ $host ]; then
    echo ", scp'ing to $host:$remote_pex_path\c"
fi
echo ''
#exit 0

if [ "$ONLYLINK" ]; then
    if [ ! -e $local_pex_path ]; then
        echo "No file at $local_pex_path"
        exit 1
    fi
else
    cd $pants_dir
    PANTS_DEV=1 ./pants src/python/twitter/pants/
    #mkdir -p $fsq_web/dist
    #cp dist/pants.pex $fsq_web/dist/
    cp dist/pants.pex $local_pex_path
fi

if [ ! $host ]; then
    ln -sf $local_pex_path $fsq_web/build-support/pants.pex
    ln -sf $local_pex_path $fsq_web/build-support/pants-current.pex
else
    scp $local_pex_path $host:$remote_pex_path && ssh $host "if [ -e foursquare.web ]; then cd foursquare.web && ln -sf $remote_pex_path build/pants.pex && ln -sf $remote_pex_path build/pants-current.pex; fi"
fi

