#!/bin/bash

if [ $# -eq 0 ]; then
  err "Must pass at least 2 args"
  exit 1
elif [ $# -eq 1 ]; then
  xargs "$0" "$1"
else
  base="$1"
  if ! isnum "$base"; then
    err "Arg 1 must be a number; found: $base"
    exit 1
  fi
  shift

  for arg in "$@"; do
    js "$arg & $base"
  done
fi
