#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  err "Must pass at least 2 args"
  exit 1
elif [ $# -eq 1 ]; then
  xargs "$0" "$1"
else
  base="$1"
  shift

  for arg in "$@"; do
    js "$arg ^ $base"
  done
fi
