#!/usr/bin/env bash

class=$1

if [ $# -ge 2 ]; then
    haystack=$2
    #echo "Finding class $class in $haystack"
else
    haystack=$(git ls-files)
    #echo "Finding class $class in any git file..."
fi

files_with_class=$(pcregrep -rl "(class|trait|object) $class[^a-zA-Z_]" $haystack)
num_files=$(count $files_with_class)

if [ $num_files -ne 1 ]; then
    echo "Error: found $num_files files with class $class:"
    echo $files_with_class
    exit 1
fi

echo $files_with_class

