#!/bin/sh

class=$1

if [ $# -ge 2 ]; then
    haystack=$2
else
    haystack=$(git ls-files)
fi

num=$(pcregrep -n "(class|trait|object) $class[^a-zA-Z_]" $haystack | cut -d: -f1)

if [ "$num" == "" ]; then
    echo "Class $class not found"
    exit 1
fi

echo $num
