#!/usr/bin/env bash

reverse=
num=
second=1
while getopts "rsn" opt; do
  case $opt in
    r)
      reverse="-r"
    ;;
    s)
      # sort output by second column
      second=2
    ;;
    n)
      second=2
      num="-n"
    ;;
  esac
done

shift $((OPTIND-1))
sort | uniq -c | sort $reverse $num -k $second "$@"
