#!/usr/bin/env bash

reverse=
num=
sort_col=1
while getopts "rsn" opt; do
  case $opt in
    r)
      reverse="-r"
    ;;
    s)
      # sort output by second column
      sort_col=2
    ;;
    n)
      sort_col=2
      num="-n"
    ;;
  esac
done

if [ $sort_col -eq 1 ]; then
 num="-n"
fi
shift $((OPTIND-1))
sort | uniq -c | sort $reverse $num -k $sort_col "$@"
