#!/usr/bin/env bash

reverse=
while [[ $# > 1 ]]; do
  arg="$1"
  shift

  case "$arg" in
    -r)
    reverse="-r"
    ;;
    *)
      break
    ;;
  esac
done

sort | uniq -c | sort $reverse -nk 1 "$@"
