#!/usr/bin/env bash

offset="$1"
shift

leaf="$(hexdump -s$offset -n1 -e '/1 "%d"' "$@")"

let count_offset=$offset+2
count="$(hexdump -s$count_offset -n2 -e '/2 "%d"' "$@")"

echo "Leaf: $leaf
Num items: $count"

let data_offset=$offset+4
if [ "$leaf" == "0" ]; then
  let data_size="$(echo "$count*24" | bc)"
  hexdump -s$data_offset -n$data_size -e '4/4 "% 9d " " " /8 "%12u" "\n"' "$@"
elif [ "$leaf" == "1" ]; then
  let data_size="$(echo "$count*32" | bc)"
  hexdump -s$data_offset -n$data_size -e '4/4 "% 9d " " " 2/8 "%u " "\n"' "$@"
else
  echo "Invalid leaf byte: $leaf" 1>&2
  exit 1
fi

let end=$data_offset+$data_size
echo "End offset: $end"
