#!/usr/bin/env bash

for arg in "$@"
do
    arg="${arg%/}"
    if [ -e "$arg.bak" ]; then
        echo "Removing $arg.bak"
        rm -rf "$arg.bak"
    fi
    echo "Moving $arg to $arg.bak"
    mv "$arg" "$arg.bak"
done
