#!/usr/bin/env bash

# copied from git-helpers

follow_links=
if [ "$1" == "-l" ]; then
  follow_links=1
  shift
fi
for file in "$@"; do
  cd "$(dirname $file)"
  file="$(basename $file)"

  if [ -n "$follow_links" ]; then
    # Iterate down a (possible) chain of symlinks
    while [ -L "$file" ]; do
      file="$(readlink "$file")"
      cd "$(dirname "$file")"
      file="$(basename $file)"
    done
  fi

  # Compute the canonicalized name by finding the physical path
  # for the directory we're in and appending the target file.
  dir="$(pwd -P)"
  echo "$dir/$file"
done
