#!/bin/bash

reverse_sort=
if [ "$1" == "-r" ]; then
  reverse_sort="-r"
  shift
fi

human_readable=
if [ "$1" == "-h" ]; then
  human_readable="-h"
  sort_human_readable="-h"
  shift
else
  sort_human_readable="-nk 1"
fi

if [ -z "$reverse_sort" -a "$1" == "-r" ]; then
  reverse_sort="-r"
  shift
fi

if [ $# -eq 0 ]; then
  du -s $human_readable ./* | sort $reverse_sort $sort_human_readable
else
  if [ $# -eq 1 -a -d "$1" ]; then
    path="${1%/}"
    du -s $human_readable "$path" "$path"/* | sort $reverse_sort $sort_human_readable
  else
    du -s $human_readable "$@" | sort $reverse_sort $sort_human_readable
  fi
fi
