#!/usr/bin/env bash

arg="$1"
if ! [[ "$arg" =~ ^[0-9]+$ ]]; then
  if [[ "$arg" =~ ^[0-9]+%[0-9]+$ ]]; then
    num="${arg##*%}"
    offset="${arg%%%*}"
  else
    err "Usage: $0 <num>"
    exit 1
  fi
else
  num="$arg"
  offset=0
fi

let offset=$offset+1
if [ $offset -eq $num ]; then
  offset=0
fi

shift
if [ $# -gt 0 ]; then
  cat "$1" | "$0" "$num"
else
  awk "NR%$num==$offset"
fi

