#!/bin/bash

arg="$1"
if ! [[ "$arg" =~ ^[0-9]+$ ]]; then
  if [[ "$arg" =~ ^[0-9]+%[0-9]+$ ]]; then
    num="${arg##*%}"
    offset="${arg%%%*}"
  else
    err "Usage: $0 <num>"
    exit 1
  fi
else
  num="$arg"
  offset=0
fi

shift
if [ $# -gt 0 ]; then
  cat "$1" | "$0" "$num"
else
  i=0
  while read -r line; do
    if [ $i -eq $offset ]; then
      echo $line
    fi
    let i=$i+1
    if [ $i -eq $num ]; then
      i=0
    fi
  done
fi

