#!/bin/bash

num=$1
if ! [[ "$num" =~ ^[0-9]+$ ]]; then
  err "Usage: $0 <num>"
  exit 1
fi

shift
if [ $# -gt 0 ]; then
  cat "$1" | "$0" "$num"
else
  i=0
  while read -r line; do
    if [ $i -eq 0 ]; then
      echo $line
    fi
    let i=$i+1
    if [ $i -eq $num ]; then
      i=0
    fi
  done
fi

