#!/usr/bin/env bash

function rrl_r() {
  new_arg="$(dirname "$1")"
  if [ "$new_arg" != "$1" ]; then
    rrl_r "$new_arg"
    ls -ld "$1"
  fi
}

for arg in "$@"; do
  rrl_r "$(canonicalize "$arg")"
done
