#!/usr/bin/env bash

if which-exists namei; then
  for arg in "$@"; do
    namei -l "$(readlink -m "$arg")"
  done
else
  for arg in "$@"; do
    arg="$(readlink -m "$arg")"
    prev=
    while [ 1 ]; do
      ls -ld "$arg"
      prev="$arg"
      arg="$(dirname "$arg")"
      if [ "$prev" == "$arg" ]; then
        break
      fi
    done | reverse-stdin | column -t -s' '
  done
fi
