#!/usr/bin/env bash

set -e

if [ $# -lt 1 ]; then
  err "Usage: $0 <from_regex> <file>"
  exit 1
fi

from_regex="$1"
shift

if [ $# -eq 1 ]; then
  haystack="$1"
  remove_haystack=0
else
  haystack="$(tmpfile)"
  cat > "$haystack"
  remove_haystack=1
fi

from="$(grep -n "$from_regex" "$haystack" | col -i : 0)"
let from=$from-1
to="$(wc -l "$haystack" | col 0)"
slice "$from" "$to" "$haystack"

if [ $remove_haystack -gt 0 ]; then
  rm -f "$haystack"
fi

