#!/usr/bin/python

import sys

args = sys.argv[1:]

start = int(args[0])
end = int(args[1])

remainder = args[2:]

if len(remainder) == 1:
    with open(remainder[0], 'r') as fd:
        num = 0
        for line in fd:
            if num >= start:
                if num >= end:
                    break
                print line,
            num += 1
else:
    print '\n'.join(remainder[start:end])
