#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  err "Usage: $0 <num> [file]"
fi

num="$1"
shift
if [ $# -gt 0 ]; then
  file="$1"
else
  file=/dev/stdin
fi

lines="$(wc -l "$file" | first)"
echo "$lines lines"

idx=0
to=0
while [ $idx -lt $num ]; do
  from=$to
  let next=$idx+1
  to="$(js "Math.floor($next * $lines / $num)")"
  echo "Chunk $idx: $from $to"
  slice $from $to $file > $file.$idx
  idx=$next
done
