#!/usr/bin/env bash

for source in "$@"; do
  source="${source%/}"
  if [ "${source:(-4)}" != ".bak" ]; then
    if [ -e "$source.bak" ]; then
      source="$source.bak"
    else
      echo "Bad argument: $source"
      continue
    fi
  fi
  dest="${source%.bak}"
  if [ -e "$dest" ]; then
    echo "Removing $dest"
    rm -rf "$dest"
  fi
  echo "Unpacking $source to $dest"
  mv "$source" "$dest"
done
