#!/usr/bin/env bash

first_file="${@: -2:1}"
second_file="${@: -1}"

args=${@:1:$((${#@} - 2))}

if [ -n "$COMM_STRIP_WHITESPACE" ]; then
  ws_cmd=strip-whitespace
else
  ws_cmd=cat
fi

comm "${args[@]}" <(sort "$first_file" | $ws_cmd) <(sort "$second_file" | $ws_cmd)

