#!/usr/bin/env bash

set -e

t1="$(mktemp)"
t2="$(mktemp)"

finish() {
  rm -f "$t1" "$t2"
}
trap finish EXIT

if [ -n "$COMM_COUNT_SORT" ]; then
  sort_cmd=sort
else
  sort_cmd=cat
fi

if [ -n "$COMM_STRIP_WHITESPACE" ]; then
  ws_cmd=strip-whitespace
else
  ws_cmd=cat
fi

cat "$1" | $ws_cmd | $sort_cmd > "$t1"
cat "$2" | $ws_cmd | $sort_cmd > "$t2"

only_first="$(comm -23 "$t1" "$t2" | wc -l)"
only_second="$(comm -13 "$t1" "$t2" | wc -l)"
both="$(comm -12 "$t1" "$t2" | wc -l)"

echo -e "${only_first}\t${only_second}\t${both}"
