#!/bin/bash

if [ $# -eq 2 ]; then
  remote="$1"
  refspec="$2"
elif [ $# -eq 1 ]; then
  remote="origin"
  refspec="$1"
else
  err "Usage: $0 [remote] <refspec>"
  exit 1
fi

non_force_cmd="git push '$remote' '$refspec' 2> /dev/null"
if eval "$non_force_cmd"; then
  exit 0
fi

dry_run_cmd="git push -f -n '$remote' '$refspec'"
echo "Non-fast-forward push? Dry-running -f: $dry_run_cmd"

if eval "$dry_run_cmd" || prompt "Continue?"; then
  cmd="git push -f '$remote' '$refspec'"
  echo "$cmd"
  eval "$cmd"
fi
