#!/bin/sh

found_remote=
found_multiple_remotes=
for remote in devbox rpi; do
  if git remote | grep -q $remote; then
    if [ ! -z $found_remote ]; then
      echo "found another eligible remote: $remote"
      found_multiple_remotes=1
    else
      echo "found remote: $remote"
      found_remote=$remote
    fi
  fi
done

if [ ! -z $found_multiple_remotes ]; then
  echo 'Found multiple eligible remotes'
  exit 1
fi

remote=$found_remote

echo "Pushing to $remote.."
git push $remote
echo "Pushed!"

staged_diff_file=$(tmpfile)
unstaged_diff_file=$(tmpfile)

git diff --cached > $staged_diff_file
git diff > $unstaged_diff_file

echo "staged diff:"
head "$staged_diff_file"
echo ''

echo "Unstaged diff:"
head "$unstaged_diff_file"
echo ''


remote_host="dev-$USER"

if [ ! -z "$REMOTE_STAGED_DIFF_FILE" ]; then
  dest_staged_diff_file="$REMOTE_STAGED_DIFF_FILE"
else
  dest_staged_diff_file="~/dc"
fi

if [ ! -z "$REMOTE_UNSTAGED_DIFF_FILE" ]; then
  dest_unstaged_diff_file="$REMOTE_UNSTAGED_DIFF_FILE"
else
  dest_unstaged_diff_file="~/d"
fi

dest_staged_diff_path="$remote_host:$dest_staged_diff_file"
dest_unstaged_diff_path="$remote_host:$dest_unstaged_diff_file"

ssh $remote_host "[[ -s $dest_staged_diff_file ]]"
if [ $? -eq 0 ]; then
  echo "ERROR: staged diff file already exists: $dest_staged_diff_path"
  exit 1
fi

ssh $remote_host "[[ -s $dest_unstaged_diff_file ]]"
if [ $? -eq 0 ]; then
  echo "ERROR: unstaged diff file already exists: $dest_unstaged_diff_path"
  exit 1
fi

if [ -s "$staged_diff_file" ]; then
  echo "Copying staged diff file $staged_diff_file to $dest_staged_diff_path"
  scp $staged_diff_file $dest_staged_diff_path
fi

if [ -s "$unstaged_diff_file" ]; then
  echo "Copying unstaged diff file $unstaged_diff_file to $dest_unstaged_diff_path"
  scp $unstaged_diff_file "$dest_unstaged_diff_path"
fi

remote_dir=$(basename $(pwd))
remote_cmd="cd $remote_dir && git reset --hard HEAD && rm -rf \$(git ls-files --other --exclude-standard) && if [ -s $dest_staged_diff_file ]; then echo 'staged'; git apply $dest_staged_diff_file; git add .; fi && if [ -s $dest_unstaged_diff_file ]; then echo 'unstaged'; git apply $dest_unstaged_diff_file; fi && rm -f $dest_unstaged_diff_file $dest_staged_diff_file"

echo "remoting: $remote_cmd"
ssh $remote_host "$remote_cmd"

