#!/usr/bin/env bash

regex='^\+\s+.*L\("'
for hash in $(git log --format="%h" $1..origin/master); do
	for f in $(git lsc $hash); do 
		git diff $hash^..$hash -- $f | pcregrep -q "$regex"
		if [ $? -eq 0 ]; then 
			echo $f
		fi
	done
done
