#!/usr/bin/env bash

suffix="$1"
shift
if [ $# -gt 0 ]; then
  for arg in "$@"; do
    echo "${arg}${suffix}"
  done
else
  while read -r line; do
    echo "${line}${suffix}"
  done
  if [ -n "$line" ]; then
    echo "${line}${suffix}"
  fi
fi
