#!/usr/bin/env bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 <prefix> <suffix>" 1>&2
  exit 1
fi

prefix="$1"
shift
suffix="$1"
shift
if [ $# -gt 0 ]; then
  for arg in "$@"; do
    echo "${prefix}${arg}${suffix}"
  done
else
  while read -r line; do
    echo "${prefix}${line}${suffix}"
  done
fi
