#!/usr/bin/env python

# Convert arguments/stdin to/from hexadecimal.

import argparse
import re
import sys

parser = argparse.ArgumentParser()
parser.add_argument(
  "-x", "--hex",
  action="store_true",
  dest="hex_input",
  help="Interpret input as hexadecimal numbers"
)

opts, args = parser.parse_known_args()

if not args:
  print(
    '\n'.join(
      map(
        chr,
        map(
          lambda s: int(s, 16 if opts.hex_input else 10),
          filter(
            len,
            re.split(
              '\s',
              sys.stdin.read()
            )
          )
        )
      )
    )
  )
else:
  print(
    ''.join(
      map(
        chr,
        map(
          lambda s: int(s, 16 if opts.hex_input else 10),
          sys.argv[1:]
        )
      )
    )
  )
