#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  xargs "$0"
  exit $?
fi

original_num_args=$#
args=$(for arg in "$@"; do echo "$arg"; done)
num_args=$(echo "$args" | wc -l)

if [ $original_num_args -ne $num_args ]; then
  echo "Error: thought we had $original_num_args but actually see $num_args."
  echo "Original args:"
  echo "$@"
  echo ''
  echo "Parsed args:"
  echo "$args"
  echo ''
  exit 1
fi

sorted_unique_args=$(for arg in "$args"; do echo "$arg"; done | sort | uniq)
num_unique_args=$(echo "$sorted_unique_args" | wc -l | tr -d ' ')

if [ $num_args -lt $num_unique_args ]; then
  echo "Error: more unique args than original args."
  echo "Original args ($num_args):"
  echo -e "\t$args"
  echo ""
  echo "Unique args ($num_unique_args):"
  echo -e "\t$sorted_unique_args"
  echo ""
  exit 1
elif [ $num_args -gt $num_unique_args ]; then

  while read -r arg; do
    echo "$args" | grep --color=never -n "^$arg\$" | head -n 1
  done <<< "$sorted_unique_args" | sort -t: -nk1 | awk -F':' '{print $2}'

else

  for arg in "$@"; do echo "$arg"; done

fi
