#!/usr/bin/env bash

v_arg=
if [ "$1" == "-v" ]; then
  v_arg="-v"
  shift
fi

args=()
if [ $# -eq 1 ]; then
  args+=("$1\$")
else
  for arg in "$@"; do
    args+=("-e")
    args+=("$arg\$")
  done
fi

grep $v_arg "${args[@]}"
