#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  xargs "$0" " "
  #delim=" "
	#echo 'Delimiter required'
	exit $?
elif [ $# -eq 1 ]; then
	xargs "$0" "$1"
	exit $?
fi

joined=
delim="$1"
shift

for arg in "$@"; do
	if [ "$joined" ]; then
		joined="${joined}${delim}"
	fi
	joined="${joined}$arg"
done
echo "$joined"
