#!/usr/bin/env python

import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument(
  "-x", "--hex",
  action="store_true",
  dest="hex_output",
  help="Output hex coords of chars"
)

opts, args = parser.parse_known_args()

str_fn = (lambda x: hex(x)[2:]) if opts.hex_output else str

if not args:
  print(
    '\n'.join(
      map(
        str_fn,
        map(
          ord,
          sys.stdin.read()
        )
      )
    )
  )
else:
  print(
    '\n'.join(
      map(
        lambda arg: ' '.join(
          map(
            str_fn,
            map(
              ord,
              arg
            )
          )
        ),
        args
     )
    )
  )
