#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo 'Delimiter required'
	exit 1
fi

delim="$1"
shift

if [ ${#delim} -eq 1 -o "$delim" == '\t' ]; then
  if [ $# -gt 0 ]; then
    cat "$@" | tr "$delim" '\n'
  else
    tr "$delim" '\n'
  fi
else
  pe "s/$delim/\n/gs" "$@"
fi
