#!/usr/bin/env bash

if [ $# -eq 0 ]; then

  while read -r line; do
    s=0
    for num in $line; do
      let s=$s+$num
    done
    echo $s
  done

else

  s=0
  for arg in "$@"; do
    let s=$s+$arg
  done
  echo $s

fi
