#!/usr/bin/env bash

s=0
if [ $# -eq 0 ]; then

  while read -r line; do
    for num in $line; do
      let s=$s+$num
    done
  done

else

  for arg in "$@"; do
    let s=$s+$arg
  done

fi

echo $s
