#!/usr/bin/env bash

if [ $# -gt 0 -a "$1" == "-v" ]; then
  shift
  needle="$1"
  shift
  #echo "looping"
  if [ $# -gt 0 ]; then
    cat "$1" | tsv -v "$needle"
    exit $?
  fi
  while read -r line; do
    #echo "read $line"
     if [ "${line:0:${#needle}}" != "$needle" ]; then
      break
    fi
    echo "$line"
  done
  echo -e "$line\n`cat -`" | column -t -s$'\t' "$@"
else
  column -t -s$'\t' "$@"
fi
