#!/usr/bin/env bash

# Append args 1: to arg 0.

filename="$1"
shift
echo -n '' > "$filename"
for arg in "$@"; do
    echo $arg >> "$filename"
done

echo "Wrote $(wc -l "$filename" | awk '{ print $1 }') lines to $filename"
