#!/bin/bash

appid="$(yarn-appid "$1")"
shift
if [ $# -gt 0 ]; then
  dest_dir="$1"
else
  dest_dir=./"$appid"
fi

mkdir -p "$dest_dir"
cd "$dest_dir"

dest_file=logs
echo "Downloading logs to $PWD/$dest_file"
yarn-logs "$appid" > "$dest_file"
du -sh "$dest_file"

split-yarn-logs "$dest_file"
rm -f "$dest_file"

