#!/usr/bin/env bash

set -e

usage() {
  err "Usage: $0 <num> <name> [other args]"
}

if [ $# -lt 1 ]; then
  usage
fi

num="$1"
shift
if [[ ! "$num" =~ [0-9]* ]]; then
  usage
fi

name="$1"
shift

find "${@:-.}" -maxdepth "$num" -name "*$name*"

