#!/usr/bin/env bash

if [ $# -lt 2 ]; then
  err "Usage: $0 <num> <name glob> [other args]"
fi

num="$1"
shift
name="$1"
shift
if [ $# -eq 0 ]; then
  args="."
else
  args="$@"
fi
find $args -maxdepth "$num" -name "*$name*"

