#!/usr/bin/env bash

if [ $# -gt 0 ]; then
  un=$1
  shift
else
  un=`unow`
fi
i=0

pe 's/.*?([\d.]+) ms/ping value=\1/' "$@" | \
pe 's/.*turned (on|off).*/\1s value=1/' | \
pe 's/.*timeout.*/timeouts value=1/' | \
grep value= | \
while read -r line; do
  s="${line%% *}"
  if [[ "$s" == "ping" || "$s" == "timeouts" ]]; then
    let i=$i+1
  fi
  let t=$un+$i
  echo "$line ${t}000000000"
done

