#!/usr/bin/env bash

if [ "${1:0:2}" == "++" ]; then
	scalaVer="$1"
	shift
fi

if [ $# -eq 0 ]; then
  sbt test $scalaVer
else
  test="$1"
  shift
  if [ $# -eq 0 ]; then
    sbt $scalaVer "$@" "test-only *$test*"
  else
    name="$1"
    shift
    sbt $scalaVer "$@" "test-only *$test* -- -z $name"
  fi
fi
