#!/usr/bin/env bash

scope=
if [ $# -eq 4 ]; then
	scope="${1}:"
	shift
fi

if [ $# -ne 3 ]; then
	echo "Usage: $0 [scope] <group> <artifact> <version>" >&2
	exit 1
fi

group="$1"
shift
artifact="$1"
shift
version="$1"
shift

sbt "${scope}what-depends-on $group $artifact $version"
