#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  sbt test
else
  test="$1"
  shift
  if [ $# -eq 0 ]; then
    sbt "$@" "test-only *$test*"
  else
    name="$1"
    shift
    sbt "$@" "test-only *$test* -- -z $name"
  fi
fi
