#!/usr/bin/env bash

set -e

if [ $# -eq 0 ]; then
  for f in `cat -`; do
    echo "Killing screen: $f"
    screen -S "$f" -X quit
  done
else
  for arg in "$@"; do
    echo "$arg"
  done | screen-quit
fi
