#!/usr/bin/env bash

set -e

screenname="$1"

if [ -z "$SCREEN_LOG_DIR" ]; then
  logfile="$(readlink -f "$1")"
else
  logfile="$SCREEN_LOG_DIR/$1"
fi

shift

if [ -e "$logfile" ]; then
  echo "Warning: $logfile already exists" 1>&2
  mv "$logfile" "$logfile".bak
fi

screenrc="`mktemp`"

echo "logfile $logfile" > "$screenrc"

screen -c "$screenrc" -L -S "$screenname" "$@"
