#!/usr/bin/env bash

set -e

tmpoutfile="$(mktemp)"

if [ $# -eq 0 ]; then
  outfile="$(mktemp)"
  tempfile=1
else
  outfile="$1"
  tempfile=
fi

finish() {
  rm -f "$tmpoutfile"
  if [ -n "$tempfile" ]; then
    rm -f "$outfile"
  fi
}
trap finish EXIT

echo -n "" > "$outfile"
prev_lines=0

for s in `screen-list-detached`; do
  screen-hardcopy "$s" "$tmpoutfile"

  echo "===== $s =====" >> "$outfile"
  cat "$tmpoutfile" >> "$outfile"
  echo "" >> "$outfile"

  cur_lines="$(wc -l "$outfile" | first)"
  let diff=$cur_lines-$prev_lines

  echo -e "$s:\t$diff lines ($cur_lines total)" 1>&2

  prev_lines=$cur_lines
done

if [ -n "$tempfile" ]; then
  cat "$outfile"
fi
