#!/usr/bin/env bash

set -e

if [ $# -eq 0 ]; then
  echo "Usage: $0 <screen ID> [output file]" 1>&2
  exit 1
elif [ $# -eq 1 ]; then
  f="$(mktemp)"
  tmpfile=1
else
  f="$2"
  tmpfile=
  if [ "${2:0:1}" != "/" ]; then
    f="$(pwd)/$f"
  fi
fi

screen -S "$1" -p0 -X hardcopy "$f"
drop-blank-lines -i "$f"

if [ -n "$tmpfile" ]; then
  cat "$f"
  rm -f "$f"
fi
