#!/usr/bin/env bash

args="$(hls -d "$@" | grep -v '^Found ' | col -1)"

OLD_IFS="$IFS"
IFS=$'\n'
for arg in $args; do
  unbakd="${arg%.bak}"
  bakd="${unbakd}.bak"
  h rm -r "$unbakd" 2> /dev/null
  h mv "$bakd" "$unbakd"
done
IFS="$OLD_IFS"
