#!/usr/bin/env bash

set -e

if [[ "$HOSTNAME" == demeter* || "$HOSTNAME" == *.mssm.edu ]]; then
  h copyToLocal "$@"
else
  src="$1"
  shift

  echo "Copying $src from HDFS to demeter.."
  tmpdir="$(ssh demeter1 "d=\"\$(mktemp -d)\"; hadoop fs -copyToLocal $src \"\$d\"/; echo \$d")"

  finally() {
    echo "Cleaning up.."
    if [ -n "$tmpdir" ]; then
      ssh demeter1 "rm -rf $tmpdir"
      echo "Removed demeter:$tmpdir"
    fi
  }

  trap finally EXIT

  echo "Copied $src into demeter:$tmpdir; scp'ing down.."
  if [ $# -eq 0 ]; then
    args=.
  else
    args=$@
  fi
  scp -r demeter1:"$tmpdir/*" "$args"
  echo "Copied from demeter"

fi
