#!/usr/bin/env bash

args="$(h ls -d "$@" | grep -v '^Found ' | col -1)"

OLD_IFS="$IFS"
IFS=$'\n'
for arg in $args; do
  h rm -r "$arg.bak" 2> /dev/null
  echo "Moving $arg to $arg.bak"
  h mv "$arg" "$arg.bak"
done
IFS="$OLD_IFS"
