#!/bin/sh

package=$1
shift
classes=$1
shift
echo "package: $package"
echo "classes: $class"

for class in $(echo $classes | tr ',' '\n'); do
    files=$(git ls-files $@ | grep ".scala$" | xargs pcregrep -l "^(?:[^/]+/)*[^/]*[^A-Za-z0-9_\.\"]$class([^A-Za-z0-9_\"]|$)" | xargs pcregrep -L "^import.*[^A-Za-z0-9_]$class([^A-Za-z0-9_]|$)" | xargs pcregrep -L "^package $package$")
    echo "files:"
    echo ""
    echo "$files"

    for f in $files; do
        file=$f outfile=$f.bak extra_line="import $package.$class" regex=import ~/s/insert_line
    done
done

