#!/bin/sh

echo "package: $package"
echo "class: $class"
files=$(git ls-files | grep ".scala$" | xargs pcregrep -l [^A-Za-z]$class | xargs grep -L "^import.*$class" | xargs pcregrep -L "^package $package")
echo "files:"
echo ""
echo "$files"

for f in $files; do
    file=$f outfile=$f.bak extra_line="import $package.$class" regex=import ~/s/insert_line
    cp $f.bak $f
    rm -f $f.bak
done