#!/usr/bin/python

import re
import sys

line = "import com.foursquare.snippet.SnippetUtils.optionalMarkup\n"

f = open(sys.argv[1], 'r')
lines = f.readlines()
f.close()

i = 0
while i < len(lines):
    if re.match("^import", lines[i]):
        found = True
        break
    i += 1

if not found:
    print "wtf"
    exit(1)

while i < len(lines) and lines[i] < line:
    i += 1

if (line != lines[i]):
    lines.insert(i, line)

f = open(sys.argv[1], 'w')
f.write(''.join(lines))
f.close()
