#!/bin/bash

formula=$1
version=$2

cd $(brew --prefix)
all_version_lines=$(brew versions $formula 2> /dev/null)
matched_version_lines=$(echo "$all_version_lines" | grep "^${version}\s")
num_found=$(echo "$matched_version_lines" | wc -l)
if [ $num_found -lt 1 ]; then
  echo "Found no matches for ${formula}@${version}:"
  echo "$all_version_lines"
  exit 1
elif [ $num_found -gt 1 ]; then
  echo "Found more than one match for ${formula}@${version}:"
  echo "$matched_version_lines"
  exit 1
fi

git_checkout_cmd=$(echo "$matched_version_lines" | perl -pe 's/^[^\s]+\s+//')
$git_checkout_cmd

brew unlink $formula
brew install $formula
brew switch $formula $version

git_checkout_head_cmd=$(echo "$git_checkout_cmd" | perl -pe 's/^git checkout [a-f0-9]+/git checkout HEAD/')
$git_checkout_head_cmd
