#!/bin/sh

num=$1
if [ ! "$num" ];
    then num=20
fi

dirs=$(head -n $num /tmp/dirs)
echo "*** Running $num dirs of $(wc -l /tmp/dirs):"
echo $dirs
./pants buildgen -linfo $dirs
if [ $? ]; then
    echo $dirs >> ~/bad_dirs
fi

sed -i.bak "1,${num}d" /tmp/dirs

