#!/bin/sh

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <hdfs path from demeter> [<local path>]"
  exit 1
fi

from=$1

if [ $# -lt 2 ]; then
  to="$HOME/sinai/data/$(basename $from)"
else
  to=$2
fi

echo "Copying from hdfs:$from to $to locally"

demeter_tmpfile=$(ssh demeter "t=\$(~/s/tmpfile); hadoop fs -copyToLocal $from \$t; echo \$t")
if [ $? != 0 ]; then
  echo "Failed demeter hadoop copyToLocal"
  exit 1
fi

echo "Copied from hdfs:$from to demeter:$demeter_tmpfile, now copying to local $to"
scp demeter:"~/$demeter_tmpfile" $to

echo "Removing demeter:$demeter_tmpfile"
ssh demeter "rm -f ~/$demeter_tmpfile"

echo "Copied to: $to"
