#!/bin/sh

set -e

if [ "$1" == "-n" ]; then
    echo "Dry run"
    dry_run=1
    shift
else
    dry_run=0
fi

for arg in $@; do
    destfile=$arg

    filename=${destfile##*/}

    mkdir -p $(dirname $destfile)

    files=$(find . -name $filename | xargs git ls-files)
    c=$(count $files)

    if [ $c -gt 1 ]; then
        echo "Error: found $c files named $filename:"
        echo $files
        exit 1
    fi

    if [ $c -eq 0 ]; then
        class=${filename%.scala}
        echo "Found no files named $filename. Attempting to find and move class $class"
        if [ $dry_run -eq 0 ]; then
            move_class $class $destfile
        fi
    else
        echo "mv $files $destfile"
        if [ $dry_run -eq 0 ]; then
            git mv -f $files $destfile
        fi
        echo "Success!"
    fi

    echo ''
done
