#!/bin/sh

echo $1
files=$(git ls-files | grep "$1")
if [ $(count $files) -eq 1 ]; then
    git log -p --follow -- $files
else
    select filename in $files; do
        git log -p --follow -- $filename
        break
    done
fi