#!/bin/bash

arg=
if [ $# -eq 1 ]; then
  if isnum $1; then
    arg="-n $1"
  fi
fi

# awesome: http://stackoverflow.com/questions/8624669/unix-head-and-tail-of-file#comment30444236_8624829
{ tee >((head $arg; echo '') >&2) | tail $arg; } 2>&1

# (head $arg; echo ''; tail $arg)
