#!/bin/bash

if [ ! "$PICARD" ]; then
  echo "Must set \$PICARD variable to a picard source root"
  exit 1
fi

version="1.107"

install-picard-facet() {
  jarname="$1"
  if [ "$facet" == "samtools" ]; then
    jarname="sam"
  fi

  jarpath="$PICARD/dist/$jarname-$version.jar"
  if [ ! -e "$jarpath" ]; then
    echo "Couldn't find $jarpath"
    exit 1
  fi

  mvn-install "$jarpath" "$version" "$1" "$1" "$HOME/.m2/repository/$1"
}

if [ $# -gt 0 ]; then
  for arg in "$@"; do
    install-picard-facet "$arg"
  done
else
  for facet in variant tribble sam picard; do
    install-picard-facet variant
  done
fi

