#!/bin/sh

verbose=
if [ "$1" == "-v" ]; then
  shift
  verbose="-v"
fi

if [ $# -eq 0 ]; then
  xargs "$0" "$verbose" "$@"
else
  all_nums=0
  for arg in "$@"; do
    if [[ $arg =~ ^[0-9]+$ ]]; then
      if [ "$verbose" ]; then
        echo "$arg"
      fi
    else
      all_nums=1
    fi
  done

  exit $all_nums
fi
