#!/bin/sh

filename=$1
pairs=$(grep -hn '^  def ' $filename | sed "s/  def \([a-zA-Z_]*\).*/\1/")
for pair in $pairs; do
	lineno=${pair%%:*}
	method=${pair##*:}
	length=$(tail -n +$lineno $filename | grep -hn '^  }' | head -n 1 | sed "s/:.*//")
	echo "$lineno: $method ($length)"
done | sort -nr -k 2 -t"("
