#!/bin/sh

# Prompt a user for a y/n response until they give you a satisfactory answer.
# Usage: `prompt <prompt> <default=y>`
# Example: $ prompt "Are you sure? [Y/n] "
# Example:
#
#   if [ $(prompt "Are you sure? [Y/n] ") ]; then
#       echo "they're sure"
#   else
#       echo "they're just not sure"
#   fi


while true; do
    echo "$1\c" 1>&2
    read line
    if [ "$line" == "" ]; then
        if [ "$2" == "" ]; then
            line="y"
        else
            line=$2
        fi
    fi
    if [ "$line" == "n" -o "$line" == "N" ]; then
        break
    fi

    if [ "$line" == "y" -o "$line" == "Y" ]; then
        echo "y"
        break
    fi

    echo "Invalid response"
done
