#!/bin/sh

old_package=$1
shift
new_package=$1
shift
# classes=$1
# shift

# for class in $(echo $classes | tr ',' '\n'); do
for class in $(classes_from_dir $@); do
    echo "class: $class"
    add_imports $new_package $class src/jvm/com/foursquare/apiserver/snippet src/jvm/com/foursquare/apiserver/liftboot test/jvm/com/foursquare/apiserver/snippet
    ./scripts/move_imports.sh $old_package.$class $new_package.$class $(git grep -l $class)
    echo ''
    echo ''
done
