#!/bin/bash

n=10
while getopts "n:" opt; do
  case $opt in
    n)
#      echo 'got n!'
#      echo all: "$@"
#      echo opt: "$opt"
#      echo 1: "$1"
#      echo ''
      n=$2
      shift
      shift
      ;;
  esac
done

#echo "$@"
#echo "$n"

h cat "$@" | head -n $n 2> /dev/null
