#!/bin/bash

if [ $# -eq 0 ]; then
  err "Usage: $0 <app id>"
  exit 1
fi

appid="$1"
if [[ $appid =~ ^[0-9]{4}$ ]]; then
  if [ -z "$yarn_appid_base" ]; then
    yarn_refresh_appid_base
  fi
  appid="application_${yarn_appid_base}_${appid}"
fi

echo "$appid"
