#!/usr/bin/env bash

if [ "$1" == "-l" ]; then

  while read -r line; do
    s=0
    for num in $line; do
      let s=$s+$num
    done
    echo $s
  done

elif [ $# -eq 0 ]; then

  s=0
  while read -r line; do
    for num in $line; do
      let s=$s+$num
    done
  done
  echo $s

else

  s=0
  for arg in "$@"; do
    let s=$s+$arg
  done
  echo $s

fi
