#!/usr/bin/env bash

handle_arg() {
  arg="$1"
  if ! [[ "$arg" =~ ^0x ]]; then
    arg="0x$arg"
  fi
  js "parseInt($arg).toString()"
}

if [ $# -eq 0 ]; then
  while read -r arg; do
    handle_arg "$arg"
  done
else
  for arg in "$@"; do
    handle_arg "$arg"
  done
fi
