#!/usr/bin/env bash

./pants clean-all
lpants $1
serial=$(cat /tmp/bn)
./pants clean-all
lpants --compile-scalac-max-parallel=3 $1
parallel=$(cat /tmp/bn)
~/s/fetch_times $serial $parallel
#echo "serial: $serial"
#echo "parallel: $parallel"
