#!/usr/bin/env bash

sort_photos()
{
grep '"url":' /tmp/$1 | sed "s/ //g" | perl -ne 'print if not /_\d+x\d+\.[a-z]+",$/' | grep playfoursquare | sed "s_.*pix/\(.*\)\",_\\1_" | sort | uniq > /tmp/s${1:0:1}
}

for f in friends checkins venue other; do sort_photos $f; done

cat /tmp/sf /tmp/so | sort > /tmp/sa
cat /tmp/sc /tmp/sv | sort > /tmp/sb


