#!/bin/sh

prefix=robo
extension=png
dir=~/Downloads/
fn="$prefix-$(date +%s)"
filepath="$dir""$fn"".$extension"

num_files=$(ls $dir$prefix*$extension | wc -l | sed "s/ *//")
#echo $num_files

# Delete robohash files if there are too many of them.
if [ $num_files -gt 5 ]; then
   ls $dir$prefix*$extension | xargs rm 
fi

curl "http://robohash.org/$fn" 2> /dev/null > $filepath && echo $filepath
