#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	xargs "$0"
else
	for arg in "$@"; do
		if [ ! -d "$s/$arg" ]; then
			echo "Module not found: $s/$arg" >&2
			continue
		fi

		if [ -d "$c/$arg" ]; then
			echo "Destination exists: $c/$arg" >&2
			continue
		fi

		echo "Moving $s/$arg to $c/$arg"
		mv "$s/$arg" "$c/$arg"
		pushd "$c/$arg"
		git init
		git add .
		git commit -m "Port from dotfiles repo"
		popd
	done
fi
