#!/usr/bin/env bash

# Prompt a user for a y/n response until they give you a satisfactory answer.
# Usage: `prompt <prompt> <default=y>`
# Example: $ prompt "Are you sure"
# Example:
#
#   if prompt "Are you sure? [Y/n]"; then
#       echo "they're sure"
#   else
#       echo "they're just not sure"
#   fi


while true; do
    echo -n "$@? [Y/n] " 1>&2
    read line
    if [ "$line" == "" ]; then
        if [ "$2" == "" ]; then
            line="y"
        else
            line=$2
        fi
    fi
    if [ "$line" == "n" -o "$line" == "N" ]; then
        exit 1
    fi

    if [ "$line" == "y" -o "$line" == "Y" ]; then
        exit 0
    fi

    echo "Invalid response"
done
