#!/usr/bin/env bash

verbose=
if [ $# -gt 0 -a "$1" == "-v" ]; then
  verbose=1
fi

log() {
  if [ -n "$verbose" ]; then
    echo "$@"
  fi
}

if [ "$IFS" == $'\n' ]; then
  if [ -z "$OLD_IFS" ]; then
    echo "ERROR: No OLD_IFS set" 1>&2
    exit 1
  else
    export IFS="$OLD_IFS"
    log "\$IFS restored"
  fi
else
  export OLD_IFS="$IFS"
  export IFS=$'\n'
  log "\$IFS now \$'\\n'"
fi
