#!/usr/bin/env bash

sort_opts=
du_opts="-sb"
while getopts "rhb" opt; do
  case $opt in
    r)
      sort_opts="$sort_opts -r"
      shift
    ;;
    h)
      du_opts="$du_opts -h"
      sort_opts="$sort_opts -h"
      shift
    ;;
    b)
      du_opts="$du_opts -b"
      shift
    ;;
  esac
done


if [ $# -eq 0 ]; then
  du $du_opts ./* | sort $sort_opts
else
  if [ $# -eq 1 -a -d "$1" ]; then
    path="${1%/}"
    du $du_opts "$path" "$path"/* | sort $sort_opts
  else
    du $du_opts "$@" | sort $sort_opts
  fi
fi
