#!/usr/bin/env bash

# Wrapper for `dirname` that:
#   * takes an optional numeric first argument (default 1) for how many directories up to go
#   * supports multiple arguments
#   * supports reading from stdin if no (non-numeric first-)arguments are passed

dirname_n() {

  if [ $1 -eq 0 ]; then
    echo $2
# NOTE(ryan): this is apparently slower?
#  elif [ $1 -eq 1 ]; then
#    dirname $2
  else
    let num_left=$1-1
    dirname_n $num_left ${2%/*}
# NOTE(ryan): this is apparently slower?
#    dirname_n $num_left $(dirname $2)
  fi
}

if isnum "$1"; then

  if [ -f "$1" ]; then
    echo "Error: ambiguous first arg: $1"
    exit 1
  fi

  num="$1"
  shift

else

  num=1

fi

if [ $# -eq 0 ]; then

  xargs "$0" "$num"

else

  for arg in "$@"; do
    dirname_n "$num" "$arg"
  done

fi
