#!/usr/bin/env bash

dest="$1"
mkdir -p "$dest"

find . -name '*.iml' | cut -d/ -f 2- | explode-parent-dirs | rsync -aOvz --no-g --no-perms --include-from=- --include='.idea' --include='.idea/**' --exclude='*' ./ "$dest"/



