name: Update submodules
on:
  push: { branches: [ all ] }
  workflow_dispatch:
jobs:
  update:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - name: "Update submodules"
        uses: runsascoded/git-update-submodules@main
        id: update
        with:
          branch: ${{ github.ref_name }}
          token: ${{ github.token }}
      - name: "Merge `all` into `server`"
        run: gh api -XPOST /repos/$GITHUB_REPOSITORY/merges -fbase=server -fhead=all '-fcommit_message=Merge `all` into `server`'
        if: github.ref_name == 'all' && steps.update.outputs.commit
        env:
          GH_TOKEN: ${{ github.token }}
