#!/bin/bash

adam_project="$1"
if [ "$adam_project" != "core" -a "$adam_project" != "cli" -a "$adam_project" != "apis" ]; then
  echo "Usage: $0 <core|cli|apis>"
  exit 1
fi

adam_project="adam-${adam_project}"

if [ ! "$ADAM" ]; then
  echo "Set the \$ADAM environment variable to the local path to an ADAM checkout."
  exit 1
fi

jars=$(find $ADAM/${adam_project}/target -maxdepth 1 -name '*.jar' | grep -v '\-tests\.jar$')
num_jars=$(count $jars)
jar=
if [ $num_jars -eq 1 ]; then
  jar="$jars"
else
  echo "Found $count jars; choose one:"
  select selected_jar in $jars; do
    jar="$selected_jar"
    break
  done
fi

version="${jar##*${adam_project}-}"
version="${version%%.jar}"

repo_path="$HOME/.m2/repository/org/bdgenomics/adam"

mvn-install "$jar" "$version" "org.bdgenomics.adam" "${adam_project}" "$repo_path"
