#!/bin/bash

if [ ! "$SPARK" ]; then
  echo "Set the \$SPARK environment variable to the local path of a spark source directory checkout."
  exit 1
fi

group="org.apache.spark"
artifact="spark-core_2.10"
version="1.0.0"
jar="$SPARK/core/target/${artifact}-${version}.jar"

mvn-install "$jar" "$version" "$group" "$artifact"
