#!/usr/bin/env bash

set -e

arg="$1"
shift

if ! [[ "$arg" =~ : ]]; then
  arg=":${arg}"
fi

tmpfile="$(mktemp)"
tmpout="$(mktemp)"
tmperr="$(mktemp)"

finish() {
  rm -f "$tmpfile" "$tmpout" "$tmperr"
}
trap finish EXIT

if ! mvn dependency:tree -Dverbose -Dincludes="$arg" -DoutputFile="$tmpfile" "$@" >"$tmpout" 2>"$tmperr"; then
  echo "Error" >&2
  cat "$tmperr" >&2
  echo '' >&2
  echo "Stdout" >&2
  cat "$tmpout" >&2
  exit 1
else
  cat "$tmpfile"
fi
