#!/usr/bin/env bash

nils=
if [ "$1" == "-0" ]; then
  nils="-0"
  shift
fi

print-tree() {
  dir="$(dirname "$1")"
  if [ "$dir" != "$1" -a "$dir" != "." ]; then
    print-tree "$dir"
  fi
  if [ -n "$nils" ]; then
    echo -e "$1\0"
  else
    echo "$1"
  fi
}

for arg in "$@"; do
  print-tree "${arg%/}"
done
